plum/port.py
setup.py

Input port required attribute override in case of valid specified default value

Release 0.7.8

---

plum/class_loader.py
plum/port.py
plum/rmq/control.py
plum/rmq/launch.py
plum/rmq/status.py
requirements.txt
test/rmq/test_status.py

Various fixes that resulted from a consolidated collaborative bug-hunt

Event loop

---

requirements.txt

Fix '==' in requirements.txt

---

plum/port.py

This allows creating nicer auto-generated documentation.

Add 'help' kwarg to OutputPort

---

plum/process_spec.py
test/test_process_spec.py

This was unfortunately missed in the last PR

Fix left over bug in ProcessSpec.get_description()

---

plumpy/ports.py
plumpy/processes.py

Fixes #26 
The output port name can now be namespaced and based on whether it
corresponds to an explicit port or not, the value will be validated
against the actual `OutputPort` or the `PortNamespace`

 Make Process.out aware of output port namespaces

---

plumpy/base_process.py
plumpy/events.py
plumpy/exceptions.py
plumpy/futures.py
plumpy/process_comms.py
plumpy/process_listener.py
plumpy/processes.py
plumpy/test_utils.py
plumpy/utils.py
plumpy/workchains.py
test/rmq/test_process_comms.py
test/test_base_process.py
test/test_processes.py
test/test_waiting_process.py

Change ProcessState names FAILED/CANCELLED to EXCEPTED/KILLED

---

plumpy/workchains.py
test/test_workchains.py

Steppers (IfStepper, FunctionStepper, WhileStepper) now tell you about
where they stand, when you do print(stepper).
This is a prerequisite for providing more helpful information in
`verdi work status`, see
aiidateam/aiida_core#1112

Issue 1112 add stepper info

---

plumpy/workchains.py
test/test_workchains.py

Add support for exit code in Return instruction

---

plumpy/ports.py

Fixes #47 
If a `PortNamespace` is not required and during validation no values
are passed, it should be considered as valid. Only when it is required
or at least one value is passed should the entire namespace be
validated

Consider a PortNamespace with required=False and no inputs as valid

---

plumpy/ports.py
test/test_port.py

Reset dynamic=False when PortNamespace valid type is set to None

---

plumpy/processes.py

Fixes #59 
This guarantees that the message makes it to the `on_killed` call
which will set the status based on this message.

Ensure that kill message is set in KilledState or KilledInterruption

---

plumpy/processes.py

Propagate the kill message from the KillInterruption to KilledState

---

plumpy/process_comms.py

[BLOCKED] Add support optional message in `pause_process` controller calls

---

plumpy/base/state_machine.py
plumpy/loaders.py
plumpy/persistence.py
plumpy/ports.py
plumpy/process_listener.py
plumpy/processes.py
plumpy/workchains.py
setup.py

Got rid of dependency on future

---

plumpy/process_comms.py

Setting this argument to True will instruct the receiver not to send
a response of the task when it is finished. This is useful for fire
and forget tasks.

Add `no_reply` argument to `ProcessController` methods

---

.pylintrc
plumpy/process_comms.py
plumpy/processes.py
test/rmq/test_process_comms.py
test/utils.py

Now a process controller can send a broadcast and any processes
listening with the same communicator settings will pick up the broadcast
and action the message.
This fixes #18

Added broadcast (play/pause/kill)_all

---

plumpy/process_comms.py

If the `load_checkpoint` call excepts, the checkpoint is most likely
corrupt and no other launcher will have a chance of successfully loading
the checkpoint and continuing the process. It makes no sense to reject
the task, which will simply lead to it being requeued by RabbitMQ.
Instead the exception should bubble up and the caller should deal with
it there.

Let exception in `load_checkpoint` in `ProcessLauncher._continue` bubble up

---

setup.py

Update dependency requirement for `pika` to `>=1.0.0`

---

README.rst

add readthedocs badge to readme

---

setup.py

Dependencies: update requirement `kiwipy==0.7.1`

---

docs/source/design_rationale.md
docs/source/index.md

@muhrin @sphuber @unkcpz, following from https://github.com/aiidateam/aiida-core/discussions/4704#discussion-2575373, I have copied some of this to a page on design rationale.
It would be good if you can add anything else here that you think would be helpful.

📚 DOCS: Add "Design Rationale" page

---

plumpy/processes.py

The broadcast can timeout on heavy loads to RMQ (see https://github.com/aiidateam/aiida-core/issues/4745).
This broadcast is not critical to running of the process, and so a timeout should not except it.
In aiida-core, the broadcast is subscribed to by `verdi process watch` (obviously not critical), in `aiida/engine/processes/futures.py:ProcessFuture` (which is unused https://github.com/aiidateam/aiida-core/issues/4758) and in `aiida/engine/runners.py:Runner.call_on_process_finish` which anyway has a backup polling mechanism on the node.
Note also, as of https://github.com/aiidateam/aiida-core/pull/4712, this timeout is configurable as `rmq.task_timeout`.
(Also ensure process pid is included in all log messages.)

👌 IMPROVE: Catch state change broadcast timeout

---

.github/workflows/ci.yml
setup.py
tox.ini

🔧 MAINTAIN: Pin tests requirements to functional versions.

---

pyproject.toml

This new release of `kiwipy` comes with support for the recent release of `aio-pika` which comes with stability fixes for the dropping of connections.

Dependencies: Update requirement `kiwipy~=0.8.2`

---

CHANGELOG.md
src/plumpy/__init__.py

Applied @sphuber reviews from https://github.com/aiidateam/plumpy/pull/299

Release `v0.23.0`

---

src/plumpy/process_comms.py
src/plumpy/process_states.py
src/plumpy/processes.py
tests/test_processes.py
tests/utils.py

The existing branch is so out of date that it was more efficient to start from scratch and just copy paste pieces. I don't want to remove the remove the contributions and conversations by force pushing therefore I create a new branch. I am still copying over things.

Implement option to force kill 
