aiidateam/plumpy

plum/port.py
plum/process.py
test/test_process.py

To determine whether a default was specified for a Port the check
if port.default
was used, which would erroneously miss the cases where a default
was set with a default value that evaluated to False. To solve
this the initial value of a Port's default value is set to the
new variable _NULL which equals an empty tuple. Checking for this
value will tell whether a user specified a default value

Fixed default port bug with defaults that evaluate to False

---

plum/class_loader.py
plum/utils.py

* Make ``ClassLoader.find_class`` a ``staticmethod`` since it doesn't use ``self``.
* Use ``rsplit`` and tuple unpacking to get ``module_path`` and ``class_name``

Simplify code of ClassLoader, load_class

---

plum/event.py
plum/persistence/pickle_persistence.py
plum/port.py
plum/process.py
plum/process_listener.py
plum/process_spec.py
plum/rmq/control.py
plum/rmq/launch.py
plum/utils.py
plum/workflow.py
test/rmq/test_status.py
test/test_attributesFrozendict.py
test/test_event.py
test/test_inputGroupPort.py
test/test_lang.py
test/test_port.py
test/test_process.py
test/test_processSpec.py
test/test_valueSpec.py
test/test_wait.py
test/test_wait_ons.py
test/test_waiting_process.py

Changes the following things:
* ``__metaclass__`` changed to ``future.utils.with_metaclass``
* ``iteritems`` changed to ``items`` etc.
* Use ``past.builtins.basestring`` instead of ``str`` and ``unicode``.
* Change ``from utils import ..`` to ``from .utils import ...`` in tests.

Add partial Python 3 support

---

plum/engine/parallel.py
plum/engine/serial.py
plum/process.py
setup.py

This contains the following changes:
* ``submit`` uses ``type(process)`` instead of hard-coding ``Process`` to get the ``run_until_complete`` method. This allows the AiiDA Process class to override the ``run_until_complete`` behavior.
* Only change the ``_state`` to ``CREATED`` if it is None before. This makes sure that the system doesn't try to re-run cached processes.
Bumps the version number to ``0.7.11``.

Support for fast-forwarding in 0.7.x

---

plum/process_spec.py
test/test_process_spec.py

The `_create_port` method of the `ProcessSpec` class contained a bug that
was not covered by the tests. When a name was passed that is namespaced
the port name was determined by popping the first element after splitting
the name on the namespace separator. However, the first element would
be the first level of the namespace and not the port name. The actual
port name is the last element of the split namespaced name. Fixed the
bug and added a test that covers this

Fix a bug in ProcessSpec._create_port

---

plum/port.py
plum/process.py
test/test_process.py

Fixes #24 
The inputs dictionary that is passed to `create_input_args` may contain
nested dictionaries to satisfy a potentially input port namespace that
contains nested port namespaces. It is important that when mapping the
input dictionaries to the nested input port namespace, the returned
dictionaries are all turned into `AttributesFrozenDict` instances

Have Process.create_input_args recurse into PortNamespaces it encounters

---

plumpy/processes.py
plumpy/utils.py
test/test_workchains.py

Adds a ``wrap_dict`` method, which turns a flat dictionary into a nested one by splitting the keys at the namespace separator. The outputs are passed to the port validation method as a nested dict, as discussed with @sphuber.

Fix output validation with namespaces

---

plumpy/processes.py

This is done so that a frozendict can be passed as input. Otherwise that
will fail because it tries to modify the frozendict.

In create_input_args, copy into a temporary dict before adding defaults

---

plumpy/base_process.py

This adds the "represent_name" YAML representer to ``ProcessStateMachineMeta``, which mean that classes of that type are YAMLed by their name.
The reason for this is to allow ``WorkChain`` classes as ``non_db`` arguments in AiiDA workchains.
See the related issue on PyYAML (about ABCMeta): https://github.com/yaml/pyyaml/issues/36

Make Process YAMLable

---

.gitignore
plumpy/__init__.py
plumpy/base/state_machine.py
plumpy/base_process.py
plumpy/processes.py
plumpy/test_utils.py
test/test_processes.py

A process needs to be able to return a result that indicates
that the result is unsuccessful. This would then indicated that
in the on_finish method, the outputs should not be checked as
the unsuccessful result already indicates that something went
wrong. If the process result did not already indicate unsuccessfulness
the outputs will be checked and if that validation fails, the
result will be marked unsuccessful after all

Implement concept of unsuccessful result in FINISHED state

---

plumpy/process_comms.py

Fixes #39 
Not sure if the method of updating the standard `KILL_MSG` dictionary with the passed `msg` is the correct one.

Ensure that KillAction passed the kill message in its msg

---

.travis.yml
plum/process.py

Fixes #43 
The raw inputs were being persisted and used to recreated the instance
upon loading from a persisted state, however, the parsed inputs were
being recreated everytime from the raw inputs. This means that the
default inputs not explicitly passed were being recreated everytime.
On the plumpy level this is not a problem, but for example in aiida-core
creating a new input node, that is not the exact same as the one created
the first time of the process creation, is problematic. To solve this we
simply persist the parsed inputs as well and reload it from the persisted
state

Persist both the raw_inputs and parsed_inputs

---

plumpy/ports.py
plumpy/process_comms.py

Fixes #45 
If the checkpoint of the process that needs to be continued cannot
be loaded, the task should be rejected

Catch exceptions thrown by load_checkpoint in ProcessLoader._continue

---

plumpy/ports.py

Fixes #49 
These arguments will be used in the creation of the new PortNamespace.
Any sub port namespaces that may have to be created along the way will
not use these arguments but have the defaults. The downside of this
approach can be easily countered by creating the sub spaces in separate
calls, which is preferable to the opposite approach where one would have
to manually reset all the properties to the defaults of the created sub
namespaces.

Allow to pass constructor kwargs for PortNamespace.create_port_namespace

---

plumpy/ports.py
plumpy/process_spec.py
plumpy/processes.py
plumpy/utils.py
test/test_expose.py

Fixes #54 
The exposing of ports of a certain ProcessSpec into a PortNamespace allows
for the definition of exclude or include rules. When the user later wants
to retrieve the exposed ports given a set of inputs, this should be mapped
on the actual exposed ports and not on the ports of the relevant ProcessSpec.
To make this possible, the actual ports that are exposed should be stored
in a memory container, indexed by the Process where the ports came from and
the namespace into which they were exposed.
Additionally, the exposing of ports can be done in an arbitrarily nested
PortNamespace. When exposing a PortNamespace of a given ProcessSpec into
oneself, one should not just copy the ports, but also all the mutable
properties of the donor PortNamespace. This is now properly implemented in …

Keep exposed port memory and overload PortNamespace attributes on absorb

---

plumpy/process_comms.py
plumpy/process_states.py
plumpy/processes.py
test/test_processes.py

Fixes #57 
This new functionality is then used by the `PauseAction` process action,
which now takes an optional message that will be set as the status attribute
of the process. Any status that might have already been set is stored, such
that when the process is unpaused, the original status can be restored.

Implement a `Process.status` attribute that can be set through ProcessActions

---

plumpy/process_comms.py

Fixes #65 
Without this call the task is acknowledged but the Process is actually
never completed in the `_launch` or `_continue` methods.

Call `step_until_terminated` in ProcessLauncher methods for nowait=True

---

plumpy/communications.py
plumpy/processes.py

Fixes #69 
This is enforced by putting an assert on the value of the communicator
in the constructor in the wrapper. This problem was found because in
the `load_instance_state` a `CommunicatorWrapper` was being instantiated
as long as the key `communicator` was present in the `load_context`
regardless of its value. This led to guards in the `Process` class for
the presence of communicator to be misled, because it would hold a
communicator wrapper, but it could not communicate, since its communicator
was None.

Ensure communicator for CommunicatorWrapper is not None

---

plumpy/persistence.py

Since the Bundle constructor requires a savable as argument which we don't have at loading time, we need to go via __new__ to bypass __init__.
Copy of PR from @greschd to get into 0.10 support branch.

Add a representer and constructor for Bundles.

---

plumpy/communications.py
test/rmq/test_communicator.py
test/test_processes.py
test/utils.py

When converting to a loop function I didn't use general (args/kwargs)
arguments for the callback and therefore the scheduled call in the event
loop would fail.
Added tests to pick this and other things up.

Fixed bug that caused broadcast messages to fail

---

plumpy/exceptions.py
plumpy/processes.py

The `add_rpc_subscriber` call on the communicator in the `init` call
of a `Process` can timeout with a `TimeoutError`, but this should not
topple the process itself. Instead, it should log the error to notify
the user that the process won't be able to respond to RPC calls. When
it is reloaded, it has another chance to add the RPC subscriber and
continue functioning normally.

Catch TimeoutError of `add_rpc_subscriber` in `Process.init`

---

plumpy/processes.py

The `remove_rpc_subscriber` call on the communicator in the `close` call
of a `Process` can fail with a `ValueError` if the process is not
actually registered as RPC subscriber, but this should not topple the
process itself, since the reason can be just that it failed to register
itself as a subscriber in the initialization of the process.

Catch `ValueError` of `remove_rpc_subscriber` in `Process.close`

---

plumpy/processes.py

In the previous commit, we already added a catch for the `ValueError`,
which would be thrown if there was no subscriber. However, the call can
also timeout which would throw a `TimeoutError` instead.

Catch `TimeoutError` of `remove_rpc_subscriber` in `Process.close`

---

plumpy/ports.py
test/test_port.py

Fixes #86 
The overridden constructor of the `OutputPort` was calling the
supers constructor incorrectly and setting a direct `_required`
attribute, overriding the `required` property of the `ValueSpec`
underneath.

Fix bug in OutputPort where `required` attribute was overridden

---

plumpy/ports.py
setup.py
test/test_port.py

Fixes #88 
Any value passed for a namespace has to be a `Mapping` type, anything
else does not make sense. This should be checked before casting it to a
dictionary which will raise if the value is not a mapping type.

Validate `port_values` is type `Mapping` in `PortNamespace.validate`

---

plumpy/ports.py
plumpy/processes.py
plumpy/workchains.py

Rename `Process._spec_type` to `Process._spec_class`

---

plumpy/processes.py
test/test_processes.py

Fixes #92 
A `Port` with a default value, nested in a non-required namespace, was
not being generated when creating an instance of the `Process` if no
explicit value was being passed for the parent namespace. The solution
is to simply create an empty dictionary for all port namespaces, even if
no explicit value is passed.

Make the default value for `PortNamespace` an empty dictionary

---

setup.py

Fixes #95 
The recently released `pika==1.0.0b2` is the last expected beta and no
more breaking changes should be introduced in the final release. The
`topika` and `kiwipy` libraries have already been updated to be
compatible with this version in `v0.2.0` and `v0.5.0`, respectively.
Since we only depend directly on `kiwipy` and `pika` we update their
version requirements.

Fix the version requirements for the `pika` and `kiwipy` dependencies

---

plumpy/processes.py
test/test_port.py
test/test_processes.py

Fixes #97 
The process specification of processes allows to define an arbitrarily
nested output namespace, however, the final results were mapped onto a
single flat namespace. In addition, the final outputs were not fully
properly validated against the process spec when the process was
finishing, causing for example required output ports that were not
explicitly output to be ignored and the process would still validate.
Here we fix the output port validation and the internal `outputs` stored
for the process will follow the exact same nesting as defined in the
outputs port namespace in the process specification.

Make the `outputs` of a `Process` follow the nesting of its spec

---

plumpy/ports.py
test/test_port.py
test/test_process_spec.py

Fixes #103 
The `validator` holds a reference to an unbound function that should be
called with the values passed to the port to validate them. The `validate`
was incorrectly passing `self` as the first argument, in addition to the
port values.

Fix call of `Portnamespace.validator`

---

.travis.yml
setup.py

Fixes #101 
The only problem is that python 3.7 still requires xenial on Travis
which doesn't come with `rabbitmq` as a service, so we have to install
manually through `sudo apt`.

Enable testing for python 3.7 on Travis

---

plumpy/persistence.py
setup.py
test/persistence/test_inmemory.py
test/rmq/test_process_comms.py
test/test_persistence.py

Add tests for InMemoryPersister and Bundle, increase test coverage of persistence.py from 85% to 93%
fix InMemoryPersister `get_process_checkpoints()` dict non-iterable Error and rewrite Bundle `from_dict()` method.

Add tests for InMemoryPersister and Bundle class

---

plumpy/processes.py

Fixes #111 
This was not being done, and so when the final value of the future was
resolved, only the tornado stack trace was shown and the value of the
original value. However, without the original traceback, debugging is
practically impossible.

Add traceback when setting exception on an excepted `Future`

---

plumpy/ports.py
test/test_expose.py

Fixes #115 
The `PortNamespace` class supports nested namespace hierarchies by
design. However, the `absorb` method, which allows one to absorb the
ports of one port namespace into another, only allows to absorb the
ports wholesale. There are many use cases where one would want to absorb
the ports, but exclude some nested ports. The `exclude` and `include`
rules did not account for this.
Here we make the `absorb` properly recursive and allow the `exclude` and
`include` rules to also target nested ports. For example if the port `a`
in the namespace `base` needs to be excluded, one can now define
`exclude=('base.a')`.

Add support for nested exclude/include rules in `PortnameSpace.absorb`

---

plumpy/lang.py
plumpy/ports.py
plumpy/workchains.py

Fixes #122 
In order to avoid some of the deprecation warnings in `pytest` here is a suggested fix for `plumpy` for some of these.

Fixed a few decprecation warnings

---

plumpy/ports.py
plumpy/process_spec.py
test/test_expose.py

Fixes #119 
Fix the implementation of `include` in `PortNamespace.absorb`
The recent introduction of support for nested namespaces in the
`exclude` and `include` rules of the `PortNamespace.absorb` method is
incorrect when `include` rules are specified. The exclude and include
rules need to be properly unwrapped to account for nesting, however,
this needs to happen at different moments. For exclude rules, namespaces
have to be done on the `leaf` level. As soon as the rule matches exactly
the port name that is considered it should be filtered.
With the include rules it works a little different. For rules
representing nested ports, all the namespaces along the way to the leaf
port *have* to be included as well.

Fix the implementation of `include` in `PortNamespace.absorb`

---

plumpy/ports.py
test/test_port.py

Fixes #117 
The current design will skip the validation of a `PortNamespace` if it
is not required *and* no values are passed for it upon process creation.
However, before validation, the inputs are pre-processed. This entails
that the input dictionary is mapped onto the input port namespace and
any input that is not explicitly specified, but corresponds to a port
with a default, has the field populated with said default value.
This behavior, however, now makes it impossible to skip the validation
of a non-required port namespace by not specifying any inputs, as soon
as it contains any port with a default. Even if no inputs are passed,
the pre-processing will populate the defaults, which will trigger the
validation because the inputs for the namespace are no longer empty.
To make it …

Add the concept of a "lazy" `PortNamespace`

---

test/rmq/test_process_comms.py

Using `yield` to wait `kill_process` to finish pass the test(no test failed after 1000 repeat). Is this the right way to fix the issue https://github.com/aiidateam/plumpy/issues/109?
However, I think the instance of class `RemoteProcessThreadController` should not run as corountine in these unittest. 
Thus the testset class `TestRemoteProcessThreadController` is no need to be the subclass of `AsyncTestCase`?

fix for issue 109

---

plumpy/workchains.py

Fixes a `collections` import that will be deprecated in 3.8.

Fixed deprecation issue for Python 3.8

---

plumpy/ports.py
test/test_port.py

Fixes #132 
During the creation of the `InputPort` the optional default value will
now be checked if it is a callable and if so evaluated first, before
validating the returned value. In `PortNamespace.pre_process` the same
check needs to be performed when the default value of a port needs to be
used, evaluating it first if the default is a callable. Note that this
is only done for defaults and not for port values themselves, even if
callables are a valid type. If one passes a callable as a value for a
port that accepts them, the user expects to get the callable back after
validation and not the evaluated value.

Allow lambdas for `InputPort` default values

---

plumpy/process_states.py
setup.py
test/test_persistence.py

Fixes #139 
Before `pyyaml==5.1` the `yaml.load` function was vulnerable to
arbitrary code execution, because it loaded the full set of YAML. There
was an alternative `safe_load` but this was not the default and could
only load a sub set of the markup language. The new version of pyyaml
deprecates the old vulnerable code and provides the `FullLoader` that
can load the full set without being vulnerable. The `safe_load` is
syntactic sugar for `load` with `Loader=FullLoader`.

Update `pyyaml` to prevent arbitrary code execution

---

plumpy/ports.py
test/test_port.py

Fixes #144 
The `dynamic` attribute was not properly toggled to `True` if
`valid_type` in constructor arguments was not `None` because the setters
were not used. All constructor arguments are now set through setters and
not directly on the attribute to make sure logic in setters is actually
executed.

`PortNamespace`: set `dynamic=True` if `valid_type` in constructor

---

plumpy/communications.py
plumpy/ports.py
plumpy/processes.py
plumpy/utils.py
test/test_communications.py

Fixes #155 
The `remove_broadcast_subscriber` method was piping through to the
`remove_task_subscriber` method, which is probably a copy and paste
error that went unnoticed because the entire class was unused and
untested.
Also change the logging level when required attribute of a `Port` is
overridden by a default from `INFO` to `DEBUG` as this is a very common
operation and was way too noisy.

Fix the `LoopCommunicator.remove_broadcast_subscriber`

---

plumpy/ports.py
test/test_expose.py
test/test_port.py

Fixes #135 
When setting `valid_type` to anything but `None` the setter will
automatically also set `dynamic` to `True`, because this almost always
what one wants and so saves having to set this attribute explicitly.
Setting a valid type for a namespace but then not allowing any value
whatsoever is non-sensical.
The `valid_type` setter also implemented the reverse, meaning that
setting `valid_type=None` would automatically set `dynamic=False`. This
use case is a lot less common and actually leads to a lot of problems
since the default `valid_type` of a namespace is `None`. When exposing a
namespace that is dynamic, but without a particular `valid_type`, which
is perfectly fine logically - it just accepts any value, the exposed
namespace would lose its dynamicity. This is because the …

`PortNamespace`: do not set `dynamic=False` when `valid_type=None`

---

release.sh

Fixes #154 
* Add explicit bash shebang
* Set the `-e` flag to exit on error
* Automatically install `twine` if it hasn't yet been installed

Robustify the release script

---

setup.py
test/pytest.ini
test/test_communications.py

Fixes #162 
The `CommunicatorHelper.add_rpc_subscriber` does not return the
identifier for `kiwipy<0.5.5`.
Add a `pytest.ini` file to ignore deprecation warnings that are being
thrown by third party libraries calling the deprecated code. These are
not warnings that we can or should address.

Update dependency requirement to `kiwipy~=0.5.5`

---

.github/workflows/ci.yml
.pre-commit-config.yaml
plumpy/persistence.py

Python 3.7.8, which was installed by default has some issues with our
requirement for `pyyaml==5.1.2`. Since we cannot release this requirement
very easily, we temporarily workaround it by pinning 3.7.7 for the tests
job, which is the only job requiring Python 3.7. Note that this required
`setup-python@v2` since v1 does not allow specifying an exact version.
Also move `yapf` to run before `pylint` in the pre-commit, such that
pylint won't complain about formatting that would have been fixed anyway
by `yapf`.

CI: Update `setup-python` action to v2 in order to pin Python to 3.7.7

---

.github/workflows/ci.yml

the github action issues is fixed. So 3.7.7
python version pining can be removed. 
https://github.com/actions/virtual-environments/issues/1202#issuecomment-670157812

ci: unpin action python version

---

CHANGELOG.md
plumpy/futures.py

Fixes #168 
Due to a bug in `contextlib._GeneratorContextManager` in versions of
Python before 3.8, once the context manager in the `run_task` coroutine
of the `futures.create_task` utility the following exception is printed
as soon as the loop is close:
Exception ignored in: <generator object create_task.<locals>.run_task>
Traceback (most recent call last):
File "../plumpy/plumpy/futures.py", line 102, in run_task
File "/usr/lib/python3.7/contextlib.py", line 158, in __exit__
AttributeError: 'NoneType' object has no attribute 'exc_info'
This exception is thrown because somehow the `sys` module is already
`None`. The only real fix would be to fix the `contextlib` module but
since this is not feasible, a workaround is introduced here that catches
this specific exception and simply …

Suppress exception thrown in generator exit in `create_task`

---

setup.py

The requirement was `aio-pika~=6.6.1` which means that the minor version
was restricted. However, for stable packages, it is often most
reasonable to allow any minor version of a particular major version,
since those should guarantee backwards compatibility.

Dependencies: relax the requirement of `aio-pika`.

---

plumpy/__init__.py
plumpy/events.py
plumpy/processes.py
test/conftest.py
test/test_events.py

Fixes #178 
A new event loop policy is implemented `PlumpyEventLoopPolicy` which
overrides the `get_event_loop` method to return an event loop that is
patched with the `nest_asyncio` library to make it reentrant. It also
makes sure that it always returns the same event loop because once made
reentrant, only a single one is required.
The policy now has to be enabled explicitly by calling the method
`set_event_loop_policy` instead of implicit, as it used to be done in
the constructor of the `Process` class. The event loop policy can be
reset through `reset_event_loop_policy`.

Make application of `nest_asyncio` patch explicit

---

plumpy/ports.py
test/test_port.py

Fixes #172 
If no value is specified for a non-required port, the validator should
not be called because there is nothing to be validated. The current
behavior of calling the validator regardless, forces all validators to
deal with the `UNSPECIFIED` value that is passed, but this is a global
constant that should remain internal to `plumpy` and not be used by
client code.

`Port`: do not call validator if unspecified and port not required

---

plumpy/processes.py
setup.py

Not explicitly adding this upper limit is not a problem for normal
installations, however, for the conda version of the package this is
problematic. The conda feedstock explicitly states that the package can
only be used with Python versions smaller than 3.7 and attempting to
install with a more recent version will fail.

Dependencies: only require `aiocontextvars` for Python < 3.7

---

.github/workflows/ci.yml
setup.py

Fixes #185 
Python 3.5 is EOL as of September 13 2020.

Drop support for Python 3.5

---

plumpy/events.py
setup.py
test/notebooks/get_event_loop.ipynb
test/test_events.py

Fixes #188 
The `PlumpyEventLoopPolicy` is designed to apply the `nest_asyncio`
patch to the event loop to make it reentrant. Once the policy is applied
using `set_event_loop_policy` the idea is that when calling
`asyncio.get_event_loop` the `get_event_loop` of `PlumpyEventLoopPolicy`
is called instead which will apply the patch to the loop if not already
done before.
However, in a Jupyter notebook, `asyncio.get_event_loop` would not
actually call the patched `get_event_loop` of the policy, even do the
policy was set. This was proved by the fact that calling the method
`asyncio.get_event_loop_policy` would return `PlumpyEventLoopPolicy`. It
was not until `asyncio.get_event_loop_policy().get_event_loop()` was
called that the patch policy was called and the loop was patched.
As a workaround …

Trigger application of nest patch in `set_event_loop_policy`

---

plumpy/mixins.py
plumpy/persistence.py

As a toy example:
```python
import plumpy
persister = plumpy.InMemoryPersister()
class PersistWorkChain(plumpy.WorkChain):
@classmethod
def define(cls, spec):
super().define(spec)
spec.outline(
cls.step1,
cls.step2,
)
def step1(self):
self.ctx.step = 1
persister.save_checkpoint(self, 'step1')
def step2(self):
self.ctx.step = 2
persister.save_checkpoint(self, 'step2')
workchain = PersistWorkChain()
workchain.execute()
{k: v['_context'] for k, v in persister._checkpoints[workchain.pid].items()}
```
```
{'step1': {'step': 2}, 'step2': {'step': 2}}
```
This obviously won't affect Persisters that serialize the data, but it is definitely a bug in this instance.
Strictly we should use `copy.deepcopy`, but this could run into issues if a value was not pickleable, and then I'm not sure how …

🐛 FIX: Allow for dereferencing of saved instance state

---

plumpy/processes.py

This is minor addition, because I want a public API to use to implement https://github.com/aiidateam/aiida-core/issues/4649#issuecomment-768439304

👌 IMPROVE: Add `Process.is_killing` property

---

.pre-commit-config.yaml
plumpy/utils.py
setup.py
test/utils.py

This package has been unmaintained for years,
and now it raises issues with python 3.8
and will not work anymore in python 3.10
closes #203

🔧 MAINTAIN: Remove frozendict dependency

---

plumpy/processes.py

The exception set on the future by `on_kill` should be retrieved,
otherwise it will be caught by the loop's exception handler.
For example on aiida-core:
```python
tests/engine/test_rmq.py .......                                                                                                                                                              [100%]
========================================================================================= warnings summary ==========================================================================================
tests/engine/test_rmq.py: 21 warnings
/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/aio_pika/message.py:714: DeprecationWarning: Use "async with message.process()" instead
warn('Use …
```

🐛 FIX: retrieve future exception on_killed

---

plumpy/process_states.py
plumpy/processes.py

See https://github.com/aiidateam/aiida-core/issues/4648#issuecomment-790870664
Currently, stopping the daemon in python 3.7 excepts all processes!

🐛 FIX: `Task.cancel` should not set state as EXCEPTED

---

plumpy/processes.py
test/test_processes.py
test/utils.py

This method is a duplicate of `Process.has_terminated`, and is not used anywhere in plumpy or aiida-core.

‼️ DEPRECATE: `Process.done` method

---

.pre-commit-config.yaml
plumpy/communications.py
plumpy/processes.py
setup.py
test/rmq/test_communicator.py
tox.ini

Filter out `state_changed` broadcasts, and allow these to pass-through without generating an asynchronous task.
The issue this "fixes" is that, currently, every time a process changes state, this causes a `run_task` asyncio Task to be created for every running process, that then has to be dealt with by the asyncio loop.
As an example, I added `print(len(asyncio.all_tasks(loop=self._loop)))` to the start of `aiida.ProcessLauncher._continue`, and submitting 100 processes (`aiida-sleep calc -n 100 -t 10 --submit`).
The peak number of tasks running rose to over 4000, which I don't imagine is helping the responsiveness of the daemon!
With this PR, the task creation is by-passed and the peak number of tasks decreases to around 150.
Note, this code could be reduced by restructuring …

👌 IMPROVE: Process broadcast subscriber

---

setup.py

Fixes #217 
The `plumpy.utils.AttributeFrozenDict` uses the base implementation of
the `frozendict` library which changed its implementation in v2.0 to not
allow the calling of `__setattr__` causing our implementation to except
in the constructor when trying to set `self._initialized = True`. Since
we dropped the dependency in `plumpy==0.16.0`, we only add this change
as a support release on the `v0.15` series. Since that is the last
version to support Python 3.6 which is not quite yet fully EOL, we want
to support this version a bit longer.

Dependencies: limit requirement for `frozendict<2.0`

---

plumpy/events.py
setup.py

It was pinned to a patch version which was causing conflicts with other
dependencies for `aiida-core`, notably `notebook`.

Dependencies: relax requirement `nest-asyncio~=1.4`

---

.github/workflows/cd.yml
.github/workflows/validate_release_tag.py

Various fixes and updates after adopting PEP 621
* Use `flit` to build and upload to PyPI
* Use string for Python version numbers instead of floats
* Install package with `pre-commit` extra for pre-commit step
* Make the tag filter regex more specific to match `vx.y.z`
* Add an explicit check to ensure tag and package version match
* Remove build on Python 3.6

Devops: update the continuous deployment workflow

---

pyproject.toml
src/plumpy/persistence.py
tox.ini

This is used in aiida-core,
to decorate the `WorkChain` class.
The problem currently is that, because of the decorator typing,
no methods defined on subclasses of `Savable`
are available for static analysers (such as IDE auto-completions).
This change ensures the output of the decorator is the same as the input.

🔧 FIX auto_persist decorator typing

---

src/plumpy/base/state_machine.py
src/plumpy/processes.py
test/test_processes.py

Fixes #219 
Before, if a state transition failed a transition to the excepted state
would be initiated. However, if the original failure came from a method
that would be called in all state transitions, i.e. also when
transitioning to the excepted, it would be guaranteed to be hit again.
In the second transition failure, the exception would simply be raised
again and bubble up.
In the case of a transition failure and so `self._transition_failed` is
set to `True`, the current state should not be explicitly exited but one
should transition straight to the excepted state.
This change now effectively allows the state machine to transition from
a `FINISHED` state to the `EXCEPTED` state. A process could transition
to the `FINISHED` state and on exiting the `FINISHED` state, an
exception could …

`StateMachine`: transition directly to excepted if transition failed 

---

pyproject.toml

Fixes #236 
The package breaks for `nest-asyncio==1.5.0` so the requirement is updated to add the lower bound `nest-asyncio>=1.5.1`.

Dependencies: Add lower limit for patch version of `nest-asyncio`

---

pyproject.toml

This latest version adds official support for Python 3.11. Also need to update `kiwipy` to `~=0.8.3` since older versions pin the `pyyaml` version to `~=5.0`.

Dependencies: Update requirement `pyyaml~=6.0`

---

docs/source/conf.py
pyproject.toml

The docs build was failing. Updating `myst-nb` solves the problem. It is
only updated to `v0.15.0` and not more recent as that is the last
version to support `sphinx~=3.5` and more recent versions of Sphinx
raise warnings with the auto API docs.

Dependencies: Update the myst-nb and sphinx requirements 

---

src/plumpy/processes.py
test/test_processes.py

Fixes #250 
The `Process.raw_inputs` property returns an `AttributesFrozenDict` instance with the inputs that were originally passed to the constructor of the process instance. These inputs should not be mutated as the final inputs are generated from it by pre-processing them with respect to the process spec, filling in defaults for missing ports.
However, the `spec().inputs.pre_process` call in `on_create` was passing a shallow copy of the `raw_inputs` and so nested dictionaries would get modified.
The problem is fixed by passing in a deep copy instead. This is done using a custom inline function `recursively_copy_dictionaries` instead of the maybe more obvious choice `copy.deepcopy`. The reason is that the latter not only copies the namespaces but also the values, which is not what we …

Process: Ensure that the raw inputs are not mutated

---

src/plumpy/ports.py
test/test_port.py

If a `valid_type` is set on a `PortNamespace` it is automatically made dynamic. If a namespace is dynamic, it means that it should accept any nested namespace, however deeply nested. However, the leafs of the inputs should still respect the `valid_type`. This was not the case though. As soon as a port namespace was made dynamic, any nested input namespace would be expected, regardless of the types of the leaf values.
The `PortNamespace.validate_dynamic_ports` is made recursive. If a port value is a dictionary, it recursively calls itself to validate its nested values, ultimately making sure that leaf values have a valid type if one is specified for the namespace.

`PortNamespace`: Fix bug in valid type checking of dynamic namespaces

---

src/plumpy/workchains.py
test/test_workchains.py

Fixes #258 
The `if_` and `while_` conditionals are constructed with a predicate. The interface expects the predicate to be a callable that returns a boolean, which if true, the body of the conditional is entered.
The problem is that the type of the value returned by the predicate was not explicitly checked, and any value that would evaluate as truthy would be accepted. This could potentially lead to unexpected behavior, such as an infinite loop for the `while_` construct.
Here the `_Conditional.is_true` method is updated to explicitly check the type of the value returned by the predicate. If anything but a boolean is returned, a `TypeError` is raised.

Workchains: Raise if `if_/while_` predicate does not return boolean

---

src/plumpy/workchains.py
test/test_workchains.py

In 800bcf154c0ea0d4576636b95d2ad2285adec266, the behavior of predicates passed to `_Conditional` instances was changed to raise if anything but a boolean was returned. This was to catch cases where users would return non-boolean values by accident, which would anyway would most likely to broken behavior of the workchain.
However, quite a number of existing implementations used to do something like the following in a predicate
def conditional_predicate(self):
if some_condition is True:
return True
In the case that `some_condition` was not equal to `True`, the predicate would return `None` which would be evaluated as "falsy" and so would function as if `False` had been returned.
In order to not break all implemenations using this behavior, `None` is still accepted and automatically …

Workchains: Accept but deprecate conditional predicates returning `None`

---

src/plumpy/workchains.py
test/test_workchains.py

Fixes #262 
In f47627adf0dece414c26254515f53fb7414bb3bf, the recently added check on the return type of a conditional predicate was updated slightly to only emit a warning when `None` would be returned instead of raising a `TypeError`. This was done because there quite a number of workchains that unwittingly were relying on this behavior and with the change added in 800bcf154c0ea0d4576636b95d2ad2285adec266 would break all of these.
Since then, it was discovered that the exception for `None` may still not be enough as it turns out that there are also quite a number of workchains that use objects that behave like booleans, but are not actually instances of the built-in `bool` base type. Examples, are `numpy.bool` as well as `aiida.orm.Bool`. Since here the behavior of the predicate would be …

Workchains: Turn exception into warning for incorrect return type in conditional predicates

---

src/plumpy/ports.py
test/test_port.py

The `dynamic` attribute of a port namespace indicates whether it should accept ports that are not explicitly defined. This was mostly used during validation, when a dictionary of port values was matched against a given `PortNamespace`.
This was, however, not being applied recursively _and_ only during validation. For example, given a dynamic portnamespace, validating a dictionary:
{
'nested': {
'output': 'some_value'
}
}
would pass validation without problems. However, the `Process.out` call that would actually attempt to attach the output to the process instance would call:
self.spec().outputs.get_port(namespace_separator.join(namespace))
which would raise, since `get_port` would raise a `ValueError`:
ValueError: port 'output' does not exist in port namespace 'nested'
The problem is that …

`PortNamespace`: Make `dynamic` apply recursively

---

.readthedocs.yml

Add the new required `build.os` key and fix it to Ubuntu 22.04

Docs: Update ReadTheDocs configuration file

---

src/plumpy/base/utils.py
src/plumpy/event_helper.py
src/plumpy/process_listener.py
src/plumpy/processes.py
src/plumpy/utils.py
test/test_processes.py
test/test_workchains.py
test/utils.py

Fixes https://github.com/aiidateam/plumpy/issues/273
We implement the persistence of ProcessListener by deriving the class ProcessListener and EventHelper from persistence.Savable. The class EventHelper is moved to a new file because of a circular import with utils and persistence
There was a circular reference issue in the test listener that was storing a reference to the process inside it, making its serialization impossible. To fix the tests an ugly hack was used: storing the reference to the process outside the class in a global dict using id as keys. Some more ugly hacks are needed to check correctly the equality of two processes. We must ignore the fact that the instances if the listener are different.
We call del on dict items of the ProcessListener's global implemented in the test …

plumpy.ProcessListener made persistent support/0.21.x

---

src/plumpy/processes.py

In `Process.on_entered`, the `Communicator.broadcast_send` method is called to broadcast the state change to subscribers over RabbitMQ. This can throw a `ChannelInvalidStateError` in addition to the `ConnectionClose` exception that was already being caught, in case there is a problem with the connection.

Catch `ChannelInvalidStateError` in process state change

---

src/plumpy/process_states.py
test/rmq/docker-compose.yml
test/test_processes.py

After some stress tests performed on plumpy to verify its conistency in state changes, i discovered an error that can be ignored: if `resume` is called on an already resumed process an `asyncio.exceptions.InvalidStateError` is raised blocking the execution of the process.
This error can happen due to some concurrent calls, and it should be ignored, since the task was already resumed successfully, also this fix is going to match the behavior of the other state transitions: calling `play` on an already running process and calling `pause` on an already paused process isn't rising any error.

Fixed resume state transition behavior

---

docs/source/tutorial.ipynb
src/plumpy/base/state_machine.py
src/plumpy/process_comms.py
src/plumpy/process_states.py
src/plumpy/processes.py
tests/base/test_statemachine.py
tests/persistence/test_inmemory.py
tests/persistence/test_pickle.py
tests/rmq/test_process_comms.py
tests/test_communications.py
tests/test_expose.py
tests/test_process_comms.py
tests/test_processes.py
tests/utils.py

Message passing with more information

---

.github/workflows/cd.yml

I don't know how to test this  ¯\\_(ツ)_/¯

Increase python version used in continuous deployment git-workflow from 3.8 to 3.12

---

src/plumpy/process_comms.py
src/plumpy/process_states.py
src/plumpy/processes.py
tests/rmq/test_process_comms.py
tests/test_processes.py

Amend for message build, now also construct message for pause operations. See the changes required in aiida-core https://github.com/aiidateam/aiida-core/pull/6668. Tests are passed.

Message interface is hidden inside function call

---

src/plumpy/processes.py

Combine with https://github.com/aiidateam/aiida-core/pull/6671, it improves the debug workflow of daemon errors with RMQ.

Make rpc callback exception more explicit and wind up to show more infos

---

src/plumpy/persistence.py
tests/rmq/test_communicator.py
tests/test_persistence.py

In https://github.com/aiidateam/plumpy/pull/221, the yaml loaders are changed to UnsafeLoader to solve the problem after new (at that time it is new, it has been three years now) PyYAML, by default it won't de/se customize type. 
The changes in https://github.com/aiidateam/plumpy/pull/221 touched two things, one was the deserializer for bundle type which the change is needed, as detail discussion in https://github.com/aiidateam/aiida-core/issues/3709 where issue was originally manifested. 
But the change of using `UnsafeLoader` also made for the kiwipy message decoder, which is not necessary. The reason that the `rmq.test_communications:test_launch_nowait` test was hanging is that the response ack message from channel is a PID which has type `uuid.UUID`. It is not a basic type that …

Handle Uuid FullLoader with yaml de/serializer
